settings:
  name: NetApp Solutions
  # search: netapp-solutions-virtualization,netapp-solutions-cloud,netapp-solutions-ai,netapp-solutions-databases,netapp-solutions-containers,netapp-solutions-dataops,netapp-solutions-sap
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: false

sidebar: 
  entries:
  - title: NetApp Solutions
    url: /index.html